# Generated by Django 2.2 on 2019-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelpCamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
