# Generated by Django 2.2 on 2019-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelpCamp', '0002_campground_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
