# Generated by Django 2.2 on 2019-05-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelpCamp', '0003_auto_20190501_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
