# Generated by Django 2.2 on 2019-04-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelpCamp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
